### ISSUE TITLE
Review/Fix eye landmarks for HCP data

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#13]
All of the eye landmarks in these files need to be visually inspected, and fixed if necessary.

```
/Shared/sinapse/CACHE/20190122_HCP_base_Results/HCP/${SUBJECT}/${SESSION}/ACPCAlign/
    BCD_ACPC_Landmarks.fcsv  # The ACPC Aligned data landmark points
    Cropped_BCD_ACPC_Aligned.nii.gz  # The ACPC Aligned dataset
```

**Comment by hjmjohnson** [comment]
Made backups of original landmark points:

```bash
for ll in $(find . -name "BCD_ACPC_Landmarks.fcsv"); do 
   cp $ii ${ii//.fcsv/_original.fcsv}
done 
```

**Comment by KKnoernschild** [comment]
LE RE AC - Delete the rest of the markups

**Comment by KKnoernschild** [comment]
probably easiest do do this in 2 parts. go through each pair , check and then save, and then open the fcsv files and delete all but the LE RE and AC points.

I already have a script written for editing strings in the fcsv files, so I can adjust that for the second part so that only the LE RE and AC points are saved and written back to the fcsv file

**Comment by KKnoernschild** [comment]
deleting extra markup points is written, currently figuring out how to hold until the image is checked and saved.

cannot read files directly from the sinapse folder, so I have 3 pairs of files on my machine for testing.

script successfully reads and deletes image node pairs when done.

**Comment by KKnoernschild** [comment]
Made a post on discourse.slicer about it , but currently have a solution that allows me to wait for key input.

slicer requires you to enter in 3 characters before the enter is read as a proper keypress in the python interpreter

So currently you have to press space 3 times and then enter before deleting the current nodes and moving on to the next subject. But you can change and move around the markups and save without interrupting the script.

I did a test with 2 subject folders and 2 fcsv/im pairs, and changed a markup in the first one and saved. when the script was done reloading I reopened the fcsv and the markup was in the new position.

Will see if people on discourse respond with something neater, but currently this works

**Comment by KKnoernschild** [comment]
Can access shared images/fcsvs through python script now, but when saving the fcsv changes I am getting a 'cannot write changes' dialogue box, and the saves are not completed

**Comment by KKnoernschild** [comment]
Finished reviewing all images/fcsvs and replacing and repositioning the eye markups where necessary

**Comment by KKnoernschild** [comment]
ran script for small amount of cases so that the only points returned are LE RE and AC.

In some cases the first line in the fcsv file was not written, and this is the line that specifies '# Markups fiducial file version = 4.6' . 

After going in by hand and adding that line in for the, I checked the backup files, and there Is no difference in the markups version string that I am checking for in the fcsv file

9 of the 25 cases I ran did not find that specific header line with the markups version. This was within the HPC folder, and after changing those files to include the markups version type header line, the PC LE RE points were labeled correctly when loaded into slicer

**Comment by KKnoernschild** [comment]
After checking a couple more , it looks like any files taht I altered were updated to markups version 4.10.

Do we want the markups version to be changed back to 4.6?

**Comment by KKnoernschild** [comment]
[Modified_BCD_ACPC_Landmark_Subjects.txt](https://github.com/BRAINSia/SINAPSE/files/3094913/Modified_BCD_ACPC_Landmark_Subjects.txt)

this list includes all subjects modified, whether it was one eye or both eyes

in the end around 30% of files needed one or both eyes repositioned

**Comment by hjmjohnson** [comment]
No longer relevant.
